version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"  # Root directory where your `pom.xml` is located
    schedule:
      interval: "daily"  # Check for updates daily; you can change to weekly or monthly
    open-pull-requests-limit: 5  # Limit the number of open PRs
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-starter"
        versions: ["<3.0.0"]  # Example to ignore versions lower than 3.0.0